"""

Ranges

See: https://www.pythoncentral.io/pythons-range-function-explained/

The range() function has two sets of parameters, as follows:

range(stop)

stop: Number of integers (whole numbers) to generate, starting from zero. eg. range(3) == [0, 1, 2].
range([start], stop[, step])

[start]: Starting number of the sequence.
[stop]: Generate numbers up to, but not including this number.
[step]: Difference between each number in the sequence.

- All parameters must be integers.
- All parameters can be positive or negative.

range() (and Python in general) is 0-index based, meaning list indexes start at 0, not 1. eg.
The syntax to access the first element of a list is mylist[0].
Therefore the last integer generated by range() is up to, but not including, stop.
For example range(0, 5) generates integers from 0 up to, but not including, 5.

"""

# 0 to 9
for i in range(10):
    print(i)

print("____________________________________________")

# 5 to 9
for i in range(5, 10):
    print(i)

print("____________________________________________")

# 0 to 8 by two (2, 4, 6, 8)
for i in range(0, 10, 2):
    print(i)

print("____________________________________________")

# Backwards - 10 to 1
for i in range(10, 0, -1):
    print(i)
